// The Daring Questions deck. Plain data — add to it freely.

export type Category = 'deep' | 'flirty' | 'silly' | 'dare'

export const CATEGORIES: Record<Category, { label: string; emoji: string; hint: string }> = {
  deep:   { label: 'Deep',   emoji: '💭', hint: 'the real stuff' },
  flirty: { label: 'Flirty', emoji: '💋', hint: 'a little spicy' },
  silly:  { label: 'Silly',  emoji: '🙃', hint: 'no wrong answers' },
  dare:   { label: 'Dare',   emoji: '🔥', hint: 'do it or forfeit' },
}

export const CARDS: Record<Category, string[]> = {
  deep: [
    'What’s something you’ve never told anyone, but want to tell me?',
    'When did you first realize you loved me?',
    'What’s a fear you have about our future?',
    'What’s one thing you wish I understood better about you?',
    'Which moment of ours would you relive if you could?',
    'What’s something you’re proud of that you rarely talk about?',
    'What does “home” mean to you?',
    'What’s a dream you gave up on — and would you pick it back up?',
    'When do you feel most loved by me?',
    'What’s a habit of mine you secretly adore?',
    'What’s the hardest thing you’ve ever forgiven?',
    'What do you want our life to look like in ten years?',
    'Is there something you need from me that you haven’t asked for?',
    'What’s a memory from childhood that shaped who you are?',
    'What’s one way I’ve changed you?',
    'What scares you most about being vulnerable?',
    'What’s a question you’ve always wanted to ask me?',
    'What part of yourself are you still learning to love?',
  ],
  flirty: [
    'What was your first impression of me — honestly?',
    'What’s the most attractive thing I do without realizing?',
    'Describe your perfect date night with me, in detail.',
    'What outfit of mine is your favorite?',
    'When was the last time I gave you butterflies?',
    'What’s a compliment you’ve wanted to give me but haven’t?',
    'Where’s the most romantic place you’d want to kiss me?',
    'What song makes you think of me?',
    'What’s one thing I do that drives you crazy — in a good way?',
    'If we had a whole day with no plans, what would you want to do with me?',
    'What’s your favorite physical feature of mine?',
    'What’s the sweetest thing I’ve ever said to you?',
    'Rate our first kiss out of ten. Explain your score.',
    'What’s a date idea you’ve been too shy to suggest?',
    'What do you think about when you miss me?',
    'What’s something about me you could stare at all day?',
  ],
  silly: [
    'If we were a crime duo, what would our heist be?',
    'Which animal do I most resemble when I wake up?',
    'If our relationship were a movie, what would it be called?',
    'What’s the weirdest thing you’ve ever googled?',
    'What food would you be, and why?',
    'If you could swap lives with me for a day, what’s the first thing you’d do?',
    'What’s the most useless talent you have?',
    'Who would play each of us in the movie of our lives?',
    'What’s your most irrational fear?',
    'If you were a ghost, who would you haunt and how?',
    'What would your entrance song be?',
    'If we opened a restaurant together, what would it serve?',
    'What’s the dumbest argument we’ve ever had?',
    'What conspiracy theory would you start about me?',
    'Describe me using only three emojis.',
    'If you had to eat one meal forever, what is it?',
  ],
  dare: [
    'Send me the last photo in your camera roll — no skipping.',
    'Do your best impression of me for 30 seconds.',
    'Sing the chorus of the last song you listened to.',
    'Text a friend “I have something to confess…” and wait 5 minutes to explain.',
    'Give me a 60-second compliment speech without pausing.',
    'Show me your most embarrassing photo.',
    'Let me post anything I want to your story (within reason).',
    'Speak in an accent for the next three rounds.',
    'Write a short love poem right now and read it out loud.',
    'Do your best runway walk across the room.',
    'Let me pick your phone wallpaper for a week.',
    'Recreate our first selfie together.',
    'Talk like a sports commentator describing what I’m doing for one minute.',
    'Slow dance with me to the next song that plays.',
    'Tell me three things you love about me in a dramatic movie-trailer voice.',
    'Try to make me laugh in 30 seconds — no touching.',
  ],
}
